spring:
  datasource:
    # Đã điền cứng Host nội bộ Railway + Database name là "railway"
    url: jdbc:mysql://root:ktCgZWKevltxPMslrhvMkujgkwSzldgv@mysql.railway.internal:3306/railway
    username: root
    # Password lấy từ hình ảnh bạn gửi
    password: ktCgZWKeVltxPMSlrhvMkujgkwSzldgv
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # QUAN TRỌNG: Dòng này giúp tự tạo bảng nếu chưa có
    hibernate:
      ddl-auto: update
    
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Các phần mail và jwt mình giữ nguyên mặc định như file cũ của bạn
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:daolelongvu1000@gmail.com}
    password: ${MAIL_PASSWORD:0986770920}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

jwt:
  signerKey: ${JWT_SIGNER_KEY:fAhsFQLtyhPPawzKmGDEU/IDeBpV7nGnIaQIWYZCzh8qGSb+ETsbFOoMfwfNsUgA}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /arigatouAirlines